services:
  mlflow:
    build:
      context: .
      dockerfile: MLflow/dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/data :/data"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge