services:
    mlflow:
      build:
        context: .
        dockerfile: MLflow/mlflow.dockerfile
      ports:
        - "5000:5000"
      volumes:
        - "${PWD}/mlflow:/home/mlflow/"
      networks:
        - app-network
networks:
  app-network:
    driver: bridge